### PR TITLE
Add Market Cabana

### PR DESCRIPTION
**Pull request by lawrencemsteven**
All this does is add the market cabana above the shop. I just wanted to keep PRs short so there will be no merge conflicts. This touches almost nothing.

### CODE REVIEW

**Comment by Jjman739** [comment]
Can you move it up 1 pixel?
image

**Comment by lawrencemsteven** [comment]
> Can you move it up 1 pixel? image

image
It looks perfect to me in 1920x1080 resolution

**Comment by lawrencemsteven** [comment]
Even in 16x9 free aspect it still looks fine. I can't move it up though cause then that 1 pixel will be shown on the bottom of every image. It should be fine though since the image is 1920x1080 for the cabana.

**Comment by Jjman739** [comment]
Aight, carry on then. 👍

**Pull request merged**
